### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by j-f1** [typicode/ghwn#7]
Currently, your code in this repository has no license. This means that by default, [nobody can use this code in another project](https://choosealicense.com/no-license/), and it is not really open source. It would be great if you could [choose an open license](https://choosealicense.com) and add it to this repository so the community can benefit from your work on this project.

**Comment by zeke** [comment]
@typicode seems to generally use the MIT license in other project.

@j-f1 perhaps you should open a PR that adds an MIT license.

**Comment by typicode** [comment]
Actually haven't hought about licensing this project, since it's just a website.
But why not I guess, thank you for the PR :)

**Comment by zeke** [comment]
Open source! 🍰
